[package]
name = "nft"
version = "1.0.0"
edition = "2021"
authors = ["mashharuki"]

[dependencies]

ink = { version = "4.0.0", default-features = false }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.3", default-features = false, features = ["derive"], optional = true }

# Include brush as a dependency and enable default implementation for PSP34 via brush feature
openbrush = { tag = "3.0.0", git = "https://github.com/727-Ventures/openbrush-contracts", default-features = false, features = ["psp34", "ownable"] }

[dev-dependencies]
ink_e2e = "4.0.0"

[lib]
name = "nft"
path = "./src/lib.rs"
crate-type = [
    # Used for normal contract Wasm blobs.
    "cdylib",
]

[features]
default = ["std"]
std = [
    "scale/std",
    "scale-info/std",

    "openbrush/std",
    # "payable_mint_pkg/std"
]
ink-as-dependency = [] 

